title: Python Programming Works
description: Personal and school works using Python language
logo: 
description: <a href="https://wei-kiat-tan.github.io/weikiat98.github.io/">Return to My Profile Page</a>
theme: jekyll-theme-minimal
