title: Python Programming Works
description: Personal works using Python language
logo: python-logo-only.png
description: <a href="https://wei-kiat-tan.github.io/weikiat98.github.io/">Return to My Profile Page</a>
theme: jekyll-theme-minimal
